server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notes-db
    username: user
    password: pass
    hikari.max-lifetime: 60000
    hikari.connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka